### ISSUE TITLE
Bad data sensor os1 readings

### ISSUE THREAD

**Issue by pamarinp** [ouster-lidar/ouster_example#120]
Hello, 

Currently we have the lidar mounted on a vehicle and we have experienced several cases when the data is corrupted in a random zone. We are using ouster_example launchfile with all the default parameters. The configuration is at 10Hz.

Here are 2 consecutive readings:

https://ibb.co/nQ9sMyX

https://ibb.co/0fNDN26

**Comment by zuzi-m** [comment]
What exactly do you mean by corrupted data? Is there data missing in the intensity/noise/range images in visualization, or is only the range missing?

If only range is missing, it can be the case of [a known issue described here.](https://github.com/ouster-lidar/ouster_example/issues/96)

If everything is missing in sections of the lidar data, it might be because the lidar sends data over a UDP network protocol which is unreliable - parts of the data are not guaranteed to arrive in the same order they were sent in, and they are not even guaranteed to be delivered at all. So it might be a case of the data packets arriving in a different order, some packets missing, or some being dropped  on the way.

**Comment by bromeara** [comment]
We have experienced similar issues and it seems to indeed be due to the UDP connection after analyzing our bag files, Are these issues that new UDP_TRANSMISSION alert could be used to detect when they're occurring or is the alert more for detecting UDP disconnects?

**Comment by HappySamuel** [comment]
Hi all,

I also faced the same issue with my OS1-16, below are the images of a stream of video
![Uploading Screenshot from 2020-02-11 16-08-36.png…]()

![Screenshot from 2020-02-11 16-08-43](https://user-images.githubusercontent.com/18137963/74219865-f84ad980-4ce8-11ea-9273-2a75e693663f.png)

![Screenshot from 2020-02-11 16-08-49](https://user-images.githubusercontent.com/18137963/74219863-f4b75280-4ce8-11ea-9537-9c57fa7578f0.png)

![Uploading Screenshot from 2020-02-11 16-09-01.png…](
![Screenshot from 2020-02-11 16-08-55](https://user-images.githubusercontent.com/18137963/74219856-f123cb80-4ce8-11ea-864e-bba435722981.png)


![Screenshot from 2020-02-11 16-09-09](https://user-images.githubusercontent.com/18137963/74219848-ea955400-4ce8-11ea-8849-8f43e0804d93.png)


![Screenshot from 2020-02-11 16-09-15](https://user-images.githubusercontent.com/18137963/74219840-e23d1900-4ce8-11ea-9216-a0ecf65d77a2.png)

**Comment by zuzi-m** [comment]
@HappySamuel it is always a good idea to upgrade the firmware and if your problem is really related to the known firmware issue then yes, it is fixed in version 1.13. There are no breaking changes between 1.12 and 1.13 so you can upgrade without having to make any other changes

**Comment by HappySamuel** [comment]
Hi @zuzi-m 

I have upgraded the os1-16 firmware to 1.13, and the above issue somehow improve, i no longer lost so much points. However the issue still persists, i saw someone named it as propeller effect. And this propeller effect only appear when the lidar mode is 2048x10 or 1024x20, any mode lower than this operate normally. Attached is the videos i recorded, hope they can explain the situation.

1024x20
![1024x20_propeller_effect](https://user-images.githubusercontent.com/18137963/74250319-631a0600-4d25-11ea-899f-2cf13927fe87.gif)

2048x10
![2048x10_propeller_effect](https://user-images.githubusercontent.com/18137963/74250325-644b3300-4d25-11ea-9b11-114e5163b916.gif)

1024x10
![1024x10_normal](https://user-images.githubusercontent.com/18137963/74250287-572e4400-4d25-11ea-80f2-ef4f87de5085.gif)

512x20
![512x20_normal](https://user-images.githubusercontent.com/18137963/74250310-60b7ac00-4d25-11ea-83f3-f437825f79b2.gif)

Please advice how shall i get rid of this propeller issue, ensuring there is no lidar packet loss?

Best,
Samuel

**Comment by adityarath302** [comment]
The issue is with your Ethernet .I had the same issue and once i changed the Ethernet port to Gbps one it stopped giving that propeller effect.

**Comment by HappySamuel** [comment]
@adityarath302 

I have been using cat7 Ethernet cable from ouster lidar box to the gigabyte network switch, as well as cat7 Ethernet cable from network switch to my PC. But the problem still persist.

Best, 
Samuel

**Comment by adityarath302** [comment]
Check your NIC ,does it support Gbps Ethernet.

**Comment by adityarath302** [comment]
The cat7 wires are fine,this is a data loss issue due to hardware not being able to capture the required points.Some hardware in between lacks Gbps functionality.Please try connecting the Lidar to the systems directly and see the results.

**Comment by HappySamuel** [comment]
Hi @adityarath302 

I will try to connect it to my system directly and see whether does this issue persist or not. 
Btw, what's NIC?

Best,
Samuel

**Comment by adityarath302** [comment]
Network Interface card

**Comment by dgarbuzov** [comment]
Even with the correct hardware, your interface may fail to negotiate a gigabit link. You can check the actual link speed with a tool like `ethtool`.

**Comment by HappySamuel** [comment]
Hi @dgarbuzov 

If my interface fail to negotiate a gigabit link, is there any solution for this?? As i have 3 same configuration, 2 of them doesn't have this propeller issue. But this one has it.

Best,
Samuel

**Comment by dgarbuzov** [comment]
Try swapping interface boxes, cables, and nics to isolate the problem. If you think the issue is with one of the interface boxes, contact ouster support for a replacement.
